### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by nickdrums** [ojcole/Password-Manager#15]
I can no longer add a new site name. When I click the "Add" button, the site name entered disappears from the input field, but the new site is not added. Permissions problem maybe?

**Comment by ojcole** [comment]
Have you tried scrolling down?

**Comment by nickdrums** [comment]
Ah!

**Comment by nickdrums** [comment]
Need to give me some feedback that the site was added - either scroll so I can see it, or show an alert maybe?

**Comment by ojcole** [comment]
Alert shown on success, red outline shown on error

**Comment by nickdrums** [comment]
Nice
